id: I0D1E16A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:21:11+00:00'
last_modified: '2022-06-09T07:59:59.290446+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016937
  title: ཤེར་སྙིང་རྣམ་བཤད་སྙིང་པོ་གསལ་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5FFB:
      image_group_id: I01JW217
      title: Volume 1 of sher snying rnam bshad snying po gsal byed
      total_pages: 240
      order: 1
      base_file: 5FFB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
