id: P007958
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:51:41.598719
source_metadata:
  id: bdr:W00EGS1016937
  title: ཤེར་སྙིང་རྣམ་བཤད་སྙིང་པོ་གསལ་བྱེད
  author: ''
  volumes:
    2777a278caff499fb1ae6a3bde4a598e:
      image_group_id: I01JW217
      title: Volume 1 of sher snying rnam bshad snying po gsal byed
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
