id: P007958
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016937
  title: ཤེར་སྙིང་རྣམ་བཤད་སྙིང་པོ་གསལ་བྱེད
  author: ''
  volumes:
    01af3aac693e4bfbb82dd78fdfe36ee9:
      image_group_id: I01JW217
      title: ''
      volume_number: 1
      total_pages: 240
ebook_metadata:
  title: ཤེར་སྙིང་རྣམ་བཤད་སྙིང་པོ་གསལ་བྱེད
  author: ''
  sku: P007958
  cover: cover.jpg
  layers:
  - pagination
